export const calendarQuotes = [
    // Years 0-10: Growth and Potential
    "Embrace the wonder of the world around you.",
    "Every day is a new adventure waiting to unfold.",
    "Learn something new and let curiosity guide you.",
    "Your potential is limitless, dream big.",
    "In every little thing, find joy and wonder.",
    "Believe in yourself and all that you can be.",
    "Every step forward is a step towards greatness.",
    "Let your imagination soar and creativity bloom.",
    "Kindness is your superpower, use it well.",
    "Every mistake is a lesson, every lesson a step forward.",

    // Years 11-20: Discovery and Self-Understanding
    "Discover who you are and what you love.",
    "In challenges, find your strength.",
    "Your uniqueness is your greatest gift.",
    "Every experience shapes your journey.",
    "Embrace change and grow from it.",
    "Believe in your dreams and chase them fiercely.",
    "Friendships are treasures, cherish them.",
    "Knowledge is power, keep learning.",
    "You are capable of amazing things.",
    "The future is yours to create.",

    // Years 21-30: Building and Pursuing Dreams
    "Build the life you envision.",
    "Every effort you make brings you closer to your goals.",
    "Embrace opportunities and make the most of them.",
    "Your hard work will pave the way to success.",
    "Believe in your abilities and pursue your passions.",
    "Make time for what truly matters.",
    "Learn from every experience and grow wiser.",
    "Stay true to your values and principles.",
    "Life is an adventure, explore it fully.",
    "Your journey is uniquely yours, embrace it.",

    // Years 31-40: Growth and Resilience
    "Embrace growth and welcome change.",
    "Resilience is your strength, persevere.",
    "Balance work with moments of joy.",
    "Cherish the bonds you build with others.",
    "In adversity, find your inner strength.",
    "Your experiences shape your wisdom.",
    "Success is a journey, not a destination.",
    "Celebrate your achievements and learn from setbacks.",
    "Stay curious and keep exploring.",
    "Life's beauty is in its impermanence, appreciate it.",

    // Years 41-50: Reflection and Legacy
    "Reflect on your journey and the lessons learned.",
    "Your legacy is built on the lives you've touched.",
    "Every moment is an opportunity to make a difference.",
    "Find joy in the present and gratitude in the past.",
    "Wisdom grows with each passing year.",
    "Cherish the memories you've created.",
    "Your experiences are a testament to your resilience.",
    "In every challenge, find a lesson.",
    "The journey is as important as the destination.",
    "Your story is a source of inspiration.",

    // Years 51-60: Wisdom and Mentorship
    "Share your wisdom and guide others.",
    "Every moment is a gift, cherish it.",
    "Find peace in the journey and joy in the present.",
    "Your experiences are valuable, share them.",
    "Mentorship is a legacy that lives on.",
    "Reflect on your accomplishments with pride.",
    "Embrace the present and look forward with hope.",
    "Your impact is measured by the lives you've touched.",
    "Gratitude is the foundation of happiness.",
    "Your journey continues to inspire.",

    // Years 61-70: Gratitude and Reflection
    "Reflect on the beauty of your journey.",
    "Gratitude brings peace and fulfillment.",
    "Every day is a new chapter in your story.",
    "Find joy in the simple pleasures of life.",
    "Your wisdom is a beacon for others.",
    "Celebrate the moments that have shaped you.",
    "Gratitude for the past brings peace to the present.",
    "Embrace the serenity of the present moment.",
    "Your life is a tapestry of cherished memories.",
    "Reflect on your journey with pride and gratitude.",

    // Years 71-80: Legacy and Peace
    "Your legacy is a life well-lived.",
    "Find peace in the wisdom of your years.",
    "Your story is a gift to future generations.",
    "Cherish the love and memories you've created.",
    "Peace comes from a life well-lived.",
    "Your wisdom is a guiding light for others.",
    "Reflect on your journey with contentment.",
    "Every moment is a treasure, appreciate it.",
    "Your legacy is the love and wisdom you leave behind.",
    "Find joy in the reflections of a life well-lived."
];
