export const quotes = [
    { id: 1, text: "Time is the most valuable thing a man can spend.", author: "Theophrastus" },
    { id: 2, text: "It is not that we have a short time to live, but that we waste a lot of it.", author: "Seneca" },
    { id: 3, text: "The present moment is the only time over which we have dominion.", author: "Thich Nhat Hanh" },
    { id: 4, text: "Dost thou love life? Then do not squander time, for that is the stuff life is made of.", author: "Benjamin Franklin" },
    { id: 5, text: "The whole future lies in uncertainty: live immediately.", author: "Seneca" },
    { id: 6, text: "You could leave life right now. Let that determine what you do and say and think.", author: "Marcus Aurelius" },
    { id: 7, text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
    { id: 8, text: "Life is short, and it is up to you to make it sweet.", author: "Sarah Louise Delany" },
    { id: 9, text: "The time is always right to do what is right.", author: "Martin Luther King Jr." },
    { id: 10, text: "The only reason for time is so that everything doesn’t happen at once.", author: "Albert Einstein" },
    { id: 11, text: "Time flies over us, but leaves its shadow behind.", author: "Nathaniel Hawthorne" },
    { id: 12, text: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
    { id: 13, text: "Lost time is never found again.", author: "Benjamin Franklin" },
    { id: 14, text: "Better three hours too soon than a minute too late.", author: "William Shakespeare" },
    { id: 15, text: "Time is what we want most, but what we use worst.", author: "William Penn" },
    { id: 16, text: "The two most powerful warriors are patience and time.", author: "Leo Tolstoy" },
    { id: 17, text: "Time takes it all, whether you want it to or not.", author: "Stephen King" },
    { id: 18, text: "They always say time changes things, but you actually have to change them yourself.", author: "Andy Warhol" },
    { id: 19, text: "Time is the wisest counselor of all.", author: "Pericles" },
    { id: 20, text: "Men talk of killing time, while time quietly kills them.", author: "Dion Boucicault" },
    { id: 21, text: "Time is the school in which we learn, time is the fire in which we burn.", author: "Delmore Schwartz" },
    { id: 22, text: "The future starts today, not tomorrow.", author: "Pope John Paul II" },
    { id: 23, text: "We must use time as a tool, not as a couch.", author: "John F. Kennedy" },
    { id: 24, text: "Time changes everything except something within us which is always surprised by change.", author: "Thomas Hardy" },
    { id: 25, text: "Time is a created thing. To say 'I don't have time' is to say 'I don't want to'.", author: "Lao Tzu" },
    { id: 26, text: "The bad news is time flies. The good news is you’re the pilot.", author: "Michael Altshuler" },
    { id: 27, text: "Time is the longest distance between two places.", author: "Tennessee Williams" },
    { id: 28, text: "Punctuality is the thief of time.", author: "Oscar Wilde" },
    { id: 29, text: "Time brings all things to pass.", author: "Aeschylus" },
    { id: 30, text: "Time stays long enough for anyone who will use it.", author: "Leonardo da Vinci" },
    { id: 31, text: "Time is a waste of money.", author: "Oscar Wilde" },
    { id: 32, text: "Time, which changes people, does not alter the image we have retained of them.", author: "Marcel Proust" },
    { id: 33, text: "Time is the most undefinable yet paradoxical of things.", author: "Charles Caleb Colton" },
    { id: 34, text: "Time is a great healer, but a poor beautician.", author: "Lucille S. Harper" },
    { id: 35, text: "Time is a physician that heals every grief.", author: "Diphilus" },
    { id: 36, text: "Time is a storm in which we are all lost.", author: "William Carlos Williams" },
    { id: 37, text: "Time is a sort of river of passing events, and strong is its current.", author: "Marcus Aurelius" },
    { id: 38, text: "Time is the cruelest teacher; first she gives the test, then teaches the lesson.", author: "Leonard Bernstein" },
    { id: 39, text: "Time is the friend of the wonderful company, the enemy of the mediocre.", author: "Warren Buffett" },
    { id: 40, text: "Time is the wisest of all things that are; for it brings everything to light.", author: "Thales" }
];
